Fix compile time warnings
Some formatting issues cause errors when using the `--warning-as-errors` compile
time flag with `mix`:

```
$ mix compile --warnings-as-errors --force
Compiled lib/hedwig/client/supervisor.ex
Compiled lib/hedwig/config.ex
lib/hedwig/handlers/help.ex:25: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)

Compiled lib/hedwig.ex
Compiled lib/hedwig/registry.ex
Compiled lib/hedwig/supervisor.ex
Compiled lib/hedwig/xml.ex
Compiled lib/hedwig/transport.ex
lib/hedwig/jid.ex:50: warning: redefining @doc attribute previously set at line 27
Compiled lib/hedwig/jid.ex
Compiled lib/hedwig/helpers.ex
Compiled lib/hedwig/xmlns.ex
Compiled lib/hedwig/conn/features.ex
Compiled lib/hedwig/handler.ex
Compiled lib/hedwig/client.ex
Compiled lib/hedwig/auth.ex
Compiled lib/hedwig/conn.ex
Compiled lib/hedwig/transports/tcp.ex
Compiled lib/hedwig/stanzas/iq.ex
Compiled lib/hedwig/stanzas/message.ex
Compiled lib/hedwig/handlers/echo.ex
Compiled lib/hedwig/handlers/great_success.ex
Compiled lib/hedwig/stanzas/presence.ex
Compiled lib/hedwig/handlers/help.ex
Compiled lib/hedwig/stanza/parser.ex
Compiled lib/hedwig/handlers/panzy.ex
Compiled lib/hedwig/stanza.ex
Compilation failed due to warnings while using the --warnings-as-errors option
```

Making some small formatting changes in the relevant files resolve these issues:
```
$ mix compile --warnings-as-errors --force
Compiled lib/hedwig/client/supervisor.ex
Compiled lib/hedwig.ex
Compiled lib/hedwig/config.ex
Compiled lib/hedwig/registry.ex
Compiled lib/hedwig/supervisor.ex
Compiled lib/hedwig/xml.ex
Compiled lib/hedwig/transport.ex
Compiled lib/hedwig/jid.ex
Compiled lib/hedwig/helpers.ex
Compiled lib/hedwig/xmlns.ex
Compiled lib/hedwig/conn/features.ex
Compiled lib/hedwig/handler.ex
Compiled lib/hedwig/client.ex
Compiled lib/hedwig/auth.ex
Compiled lib/hedwig/conn.ex
Compiled lib/hedwig/transports/tcp.ex
Compiled lib/hedwig/stanzas/iq.ex
Compiled lib/hedwig/stanza/parser.ex
Compiled lib/hedwig/stanzas/message.ex
Compiled lib/hedwig/handlers/echo.ex
Compiled lib/hedwig/stanzas/presence.ex
Compiled lib/hedwig/handlers/great_success.ex
Compiled lib/hedwig/handlers/panzy.ex
Compiled lib/hedwig/handlers/help.ex
Compiled lib/hedwig/stanza.ex
Generated hedwig app
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
```